name: ✨ Feature
description: Suggest a new feature or enhancement
title: "[Feature] <title>"
labels: ["enhancement", "triage"]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!
    validations:
      required: false
